theme_color:
#  primary: indigo
  primary: cyan
  accent: pink

notice:

favicon: /images/favicon.png
banner: /images/banner.png
avatar: https://cdn.openpy.org/avatar.png
rss: /atom.xml

email:
sns:
  twitter:
  facebook:
  google_plus:
  weibo: https://weibo.com/u/5818507385
  instagram:
  tumblr:
  github: https://github.com/Desmond56
  linkedin:
  zhihu:
  douban:
  qq: 718195373
  wechat:

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id: 155720019
  baidu_site_id:
  cnzz_site_id:

pages:
  - name: 标签云
    link: /tagcloud
  - name: 画廊
    link: /gallery
links:

since:
footer_text:
license:

gallery:
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js
  lazyload_js: https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi:
  site: false
  page: false
  busuanzi_js: http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: 发送到手机
  use: online
donate:
search:
  placeholder: 请输入关键字
  path: /search.xml
  use: online
comment:
  use: gitalk
  disqus_shortname:
  gitalk_client_id: 2940f637db3aa14eb98d
  gitalk_client_secret: 9ddf486c5e61566535f41fbe9dd867a514616f13
  gitalk_repo: gitalk
  gitalk_owner: Desmond56
  gitalk_sid_type:
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
